name: excel
version: 4.0.3


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.0.0
  xml: ">=5.0.0 <7.0.0"
  collection: ^1.15.0
  equatable: ^2.0.0

dev_dependencies:
  test: ^1.23.0
  lints: ^2.1.0
